version: '3'
services:
  poverty_dev:
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - /usr/share/nginx/poverty/collect_static/:/usr/share/nginx/poverty/collect_static/
      - /etc/localtime:/etc/localtime
      - /usr/share/nginx/poverty/logs/:/usr/share/nginx/poverty/logs/
    image: poverty_dev
    depends_on:
      - redis
    container_name: dev_poverty
    command: gunicorn -c gunicorn-dev.py poverty.wsgi:application
  redis:
    restart: always
    image: redis:latest
    container_name: dev_poverty_redis
    hostname: redis
    volumes:
      - ./redis/data:/data
      - /etc/localtime:/etc/localtime
  celery-worker:
    restart: always
    depends_on:
      - redis
      - poverty_dev
    image: poverty_dev
    container_name: dev_poverty_celery_worker
    volumes:
      - /etc/pki/:/etc/pki/
      - /etc/localtime:/etc/localtime
    command: celery -A poverty.celery worker -l info -P gevent -Q celery,email
  celery-beat:
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
    image: poverty_dev
    depends_on:
      - redis
      - poverty_dev
    container_name: dev_poverty_celery_beat
    command: celery -A poverty.celery beat --loglevel=debug
  flower:
    image: poverty_dev
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - '5600:5555'
    container_name: dev_poverty_flower
    command: celery flower -A poverty.celery --purge_offline_workers=True --loglevel=info --url_prefix=flower
    depends_on:
      - redis
      - celery-worker